### ISSUE TITLE
Wrong repo name in README

### ISSUE THREAD

**Issue by GJKrupa** [matthieusb/zsh-sdkman#6]
The Antigen and ZGen installation instructions reference the repo name `matthieusb/zsh-zsdkman` which does not exist.  I assume this is a typo and should be `matthieusb/zsh-sdkman`.

**Comment by matthieusb** [comment]
Oh yes indeed, this is a typo. Correction is on the way. Thanks !

**Comment by matthieusb** [comment]
Done !
